
# This is the main configuration file for Supabase CLI
# For full documentation of available options, check https://supabase.com/docs/guides/cli/config

project_id = "ftgtlhdocyixykjkbfpr"

[api]
enabled = true

[db]
# Don't use shadow migrations 
port = 5432

[studio]
enabled = true
port = 8000

[auth]
enabled = true

[storage]
enabled = true

[realtime]
enabled = false

[analytics]
enabled = false

[functions]
[functions.main]
enabled = true
