
# This is the main configuration file for Supabase CLI
# For full documentation of available options, check https://supabase.com/docs/guides/cli/config

project_id = "ftgtlhdocyixykjkbfpr"

[api]
enabled = true

[db]
# Don't use shadow migrations 
port = 5432

[studio]
enabled = true
port = 8000

[auth]
enabled = true

[storage]
enabled = true

[realtime]
enabled = false

[analytics]
enabled = false

[functions]
[functions.cancel-subscription]
verify_jwt = true
[functions.change-subscription-plan]
verify_jwt = true
[functions.check-stripe-status]
verify_jwt = false
[functions.create-checkout-session]
verify_jwt = true
[functions.create-customer-portal-session]
verify_jwt = true
[functions.stripe-webhook]
verify_jwt = false
[functions.sync-plan-with-stripe]
verify_jwt = true
[functions.update-payment-method]
verify_jwt = true
