// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftgtlhdocyixykjkbfpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0Z3RsaGRvY3lpeHlramtiZnByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1ODEyMTYsImV4cCI6MjA1NjE1NzIxNn0.s8HecgCJQOsuM8qiidLASVTWllyvJH7NAoizscI7YRk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);